name: Packer Create Image for Node.js App

on:
  push:
    branches:
       - demo 
jobs:
  packer-buildimage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      #Make webapp.zip inside packer
      - name: Zip Web App
        run: |
          set -e
          mkdir webapp                     
          cp -r $(ls -A | grep -v '^webapp$') webapp/                
          zip -r webapp.zip webapp -x "webapp/node_modules/*" "webapp/.git/*" 
          mv webapp.zip packer/

      # Set up AWS CLI for authentication
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Authenticate with Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          
      # Install Packer using the official GitHub Action
      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        run: |
          set -e
          cd packer
          packer init .

       # Building a custom image for AWS & GCP in parallel using Packer
      - name: Build Custom Image with Packer
        id: packer
        run: |
          set -e
          cd packer
          packer build .

          AWS_AMI_ID=$(aws ec2 describe-images --owners ${{ secrets.AWS_DEV_ACCOUNT_ID }} --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text)
          GCP_IMAGE_ID=$(gcloud compute images list --no-standard-images --format="table(NAME,CREATION_TIMESTAMP)" --sort-by="CREATION_TIMESTAMP" | tail -n 1)

          if [ -n "$AWS_AMI_ID" ]; then
            echo "New AMI created: $AWS_AMI_ID"
            echo "AWS_AMI_CREATED=true" >> $GITHUB_OUTPUT
            echo "AWS_AMI_ID=$AWS_AMI_ID" >> $GITHUB_OUTPUT
          else
            echo "No new AMI was created"
            echo "AWS_AMI_CREATED=false" >> $GITHUB_OUTPUT
          fi

          if [ -n "$GCP_IMAGE_ID" ]; then
            echo "New GCP Image created: $GCP_IMAGE_ID"
            echo "GCP_IMAGE_CREATED=true" >> $GITHUB_OUTPUT
            echo "GCP_IMAGE_ID=$GCP_IMAGE_ID" >> $GITHUB_OUTPUT
          else
            echo "No new GCP Image was created"
            echo "GCP_IMAGE_CREATED=false" >> $GITHUB_OUTPUT
          fi

      # Share the AMI with the DEMO AWS account
      - name: Share AMI with Demo Account
        if: steps.packer.outputs.AWS_AMI_CREATED == 'true'
        run: |
          aws ec2 modify-image-attribute --image-id ${{ steps.packer.outputs.AWS_AMI_ID }} \
            --launch-permission '{"Add":[{"UserId":"${{ secrets.AWS_DEMO_ACCOUNT_ID }}"}]}'

      # Share the image with the DEMO GCP project
      - name: Share GCP Image with DEMO Account
        if: steps.packer.outputs.GCP_IMAGE_CREATED == 'true'
        run: |
          gcloud compute images add-iam-policy-binding ${{ steps.packer.outputs.GCP_IMAGE_ID }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --member="serviceAccount:${{ secrets.GCP_DEMO_ACCOUNT_EMAIL }}" \
            --role="roles/compute.imageUser"
